language: python
sudo: required
dist: trusty
cache:
  directories:
    - $HOME/.ivy2
    - $HOME/spark
    - $HOME/.cache/pip
    - $HOME/.pip-cache
    - $HOME/.sbt/launchers
jdk:
  - oraclejdk8
python:
  - 3.6
sudo: false
addons:
  apt:
    packages:
      - axel
cache: pip
before_install:
  - export PATH=$HOME/.local/bin:$PATH
  - pip install -U pip
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
install:
  # Download spark 2.3.1
  - "[ -f spark ] || mkdir spark && cd spark && axel http://www-us.apache.org/dist/spark/spark-2.3.3/spark-2.3.3-bin-hadoop2.7.tgz && cd .."
  - "tar -xf ./spark/spark-2.3.3-bin-hadoop2.7.tgz"
  - "export SPARK_HOME=`pwd`/spark-2.3.-bin-hadoop2.7"
  - "export PYTHONPATH=$PYTHONPATH:$SPARK_HOME/python"
  - echo "spark.yarn.jars=$SPARK_HOME/jars/*.jar" > $SPARK_HOME/conf/spark-defaults.conf
  - pip install -r requirements.txt
script:
  - pytest $HOME/handyspark/tests
